export const API_ENDPOINTS = {
  PRODUCTS: '/commerce/products/',
  GETALLDETAILS:"/commerce/web/catalog/",
  PRODUCTS_POPULAR: '/popular-products',
  PRODUCTS_REVIEWS: '/reviews',
  PRODUCTS_REVIEWS_ABUSE_REPORT: '/abusive_reports',
  ADDRESS:"/commerce/customer-address/",
  ADD_CART:"/commerce/cart/add_product/",
  ADD_ADDRESS_TO_CART:"/commerce/cart/add_address/",
  GET_CART:"/commerce/cart/all/",
  CART_PLACE_ORDER:'/commerce/cart/place_order/',
  PRODUCTS_QUESTIONS: '/questions',
  FEEDBACK: '/feedbacks',
  CATEGORIES: '/commerce/category',
  FAQ:"/meta/faq/",
  COUNTRY:"/meta/country/",
  CHANGE_COUNTRY:'/auth/change-country/',
  TYPES: '/types',
  TAGS: '/tags',
  SHOPS: '/shops',
  AUTHORS: '/authors',
  AUTHORS_TOP: '/top-authors',
  MANUFACTURERS: '/manufacturers',
  MANUFACTURERS_TOP: '/top-manufacturers',
  COUPONS: '/coupons',
  COUPONS_VERIFY: '/coupons/verify',
  GET_ADDRESS:'/commerce/customer-address/',
  PLACE_ORDER:'/commerce/cart/place_order/',
  ORDERS: '/commerce/order/',
  NOTE:'/commerce/cart/update_note/',
  ORDERS_REFUNDS: '/refunds',
  ORDERS_PAYMENT: '/make_payment/',
  REFERESH_PAYMENTS:"/refresh_order_payments/",
  ORDERS_CHECKOUT_VERIFY: '/orders/checkout/verify',
  ORDERS_DOWNLOADS: '/downloads',
  GENERATE_DOWNLOADABLE_PRODUCT_LINK: '/downloads/digital_file',
  USERS: '/users',
  USERS_ADDRESS: '/address',
  USERS_ME: '/auth/get-user-info/',
  USERS_LOGIN: '/auth/login/',
  USERS_REGISTER: '/auth/register/',
  USERS_FORGOT_PASSWORD: '/auth/reset-password/',
  USERS_VERIFY_FORGOT_PASSWORD_TOKEN: '/auth/validate-reset-password-otp/',
  USERS_RESET_PASSWORD: '/auth/set-new-password/',
  USERS_CHANGE_PASSWORD: '/auth/updated-password/',
  USERS_LOGOUT: '/logout',
  USERS_SUBSCRIBE_TO_NEWSLETTER: '/subscribe-to-newsletter',
  USERS_CONTACT_US: '/meta/contact-us/',
  USERS_WISHLIST: '/my-wishlists',
  WISHLIST: '/wishlists',
  USERS_WISHLIST_TOGGLE: '/wishlists/toggle',
  SOCIAL_LOGIN: '/social-login-token',
  SEND_OTP_CODE: '/send-otp-code',
  VERIFY_OTP_CODE: '/auth/validate-otp/',
  OTP_LOGIN: '/otp-login',
  UPDATE_CONTACT: '/update-contact',
  SETTINGS: '/settings',
  UPLOADS: '/attachments',
  MY_QUESTIONS: '/my-questions',
  MY_REPORTS: '/my-reports',
  CARDS: '/cards',
  SET_DEFAULT_CARD: '/set-default-card',
  SAVE_PAYMENT_METHOD: '/save-payment-method',
  PAYMENT_INTENT: '/payment-intent',
  BEST_SELLING_PRODUCTS: '/best-selling-products',
  SEND_VERIFICATION_EMAIL: '/email/verification-notification',
  USERS_UPDATE_EMAIL: '/update-email',
  STORE_NOTICES: 'store-notices',
  NEAR_SHOPS: '/near-by-shop',
};
