export { FruitsVegetable } from './fruits-vegetable';
export { FacialCare } from './facial-care';
export { Handbag } from './handbag-icon';
export { DressIcon } from './dress-icon';
export { FurnitureIcon } from './furniture-icon';
export { BookIcon } from './book-icon';
export { MedicineIcon } from './medicine-icon';
export { Restaurant } from './restaurant-icon';
export { Bakery } from './bakery-icon';
export { Toys } from "./toy-icon"
export { Kids } from "./kids-icon"
export { Ridder } from "./ridders-icon"
export { Stationary } from "./stationary-icon"
export { PlayAreaItems } from "./play-area-icon"
export { Accessories } from "./accessories-icon"